name: 'Package OpenWrt with flippy script'
author: 'mingxiaoyu'
description: 'Use the flippy script package Armvirt as OpenWrt'
inputs:
  types:
    description: 'The type of the drive'
    required: true
    default: s905d
  openwrt-version:
    description: 'The openwrt version'
    required: false
  kernel-version:
    description: 'The kernel version'
    required: false
    default: Latest
  whoami:
    description: 'The name of build the openwrt'
    required: false
    default: mingxiaoyu
  out:
    description: 'The output path of the openwrt'
    required: false
    default: /out
  openwrt-path:
    description: 'The input path of the openwrt'
    required: false
  openwrt-url:
    description: 'The url of the openwrt'
    required: false
  sub-name:
    description: 'add the sub name in file: xxxx-xx-{sub-name}.img.gz'
    required: false
  githubrepository:
    description: 'the repository of the openwrt core'
    required: false
    default: mingxiaoyu
outputs:
  status:
    description: 'The status of the action'
    value: ${{ steps.package.outputs.status }}
runs:
  using: 'node12'
  main: 'dist/index.js'
