name: openwrt path test

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-18.04
    name: test
  
    steps:   
    - name: Initialization environment
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
        cd /workdir
        sudo mkdir openwrt
        sudo chown $USER:$GROUPS openwrt
        cd openwrt
        wget https://github.com/mingxiaoyu/N1Openwrt/releases/download/2021052718/openwrt-armvirt-64-default-rootfs-mini.tar.gz -O test.tar.gz
        wget https://github.com/mingxiaoyu/N1Openwrt/releases/download/2021052718/update-amlogic-openwrt.sh

        sudo mkdir -p /upload
        sudo chown $USER:$GROUPS /upload
        
        cd /upload
        echo "UPLOAD=$PWD" >> $GITHUB_ENV
        
    - name: Install the package
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install xz-utils btrfs-progs gawk zip unzip curl dosfstools  uuid-runtime
        sudo -E apt-get -qq install git  git-core
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt 
 
    - name: check1
      run: |
        cd openwrt
        ls
        
    - name: Package OpenWrt with flippy script
      uses: mingxiaoyu/package-flippy-openwrt@dev
      id: package
      with:
        types: s905d
        out: ${{ env.UPLOAD }}
        openwrt-path: openwrt
        
    - name: check
      run: |
        echo "out:${{ steps.package.outputs.out }}"
        echo "status:${{ steps.package.outputs.status }}"
        
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: upload
        path: ${{env.UPLOAD}}
